name: Daily Catholic Readings Scraper

on:
  schedule:
    - cron: "30 21 * * *" # Runs every day at 03:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape_readings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install selenium beautifulsoup4

      - name: Run Scraper
        run: python scrapper.py

      - name: Commit and Push Updated Readings
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add readings.json
          git diff --cached --quiet || (git commit -m "Updated daily readings" && git push)
